// this is the second assignment

// Create a command line-based guessing game, the game should guess a random number between 1 and 10, accept your input (a number you guess within the range of 1 to 10), compare your input with the random number generated.


// If the inputs are same, the output should be “You have won!”
 
// If the imputs are not the same the output should be “You have lost! The random number generated is <randomNumber>”.

// "<randomNumber>" is a placeholder (where the random number generated by NodeJS should be placed).

const readline = require('readline');
const randomNum = Math.floor(Math.random() * 10) + 1;
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

let playAgain = true;

function askQuestion() {
  rl.question('Guess the number between 1 and 10\n', (guess) => {
    if (guess === 'quit') {
      console.log('Thanks for playing!');
      rl.close();
    } else if (guess == randomNum) {
      console.log('You guessed it!');
      rl.question('Do you want to play again? (yes or no)\n', answer => {
        if (answer === 'yes') {
          askQuestion();
        } else {
          console.log('Thanks for playing!');
          rl.close();
        }
      });
    } else {
      console.log(`Sorry, the number was ${randomNum}`);
      askQuestion();
    }
  });
}

askQuestion();