// this is the second assignment


// Create a command line-based guessing game, the game should guess a random number between 1 and 10, accept your input (a number you guess within the range of 1 to 10), compare your input with the random number generated.


// If the inputs are same, the output should be “You have won!”
 
// If the imputs are not the same the output should be “You have lost! The random number generated is <randomNumber>”.

// "<randomNumber>" is a placeholder (where the random number generated by NodeJS should be placed).

const { log } = require('console');
const readline = require('readline');
let rl = readline.createInterface(
  process.stdin, 
  process.stdout);

let randomNumber = Math.floor((Math.random() * 10) + 1)

let playagain = true;

let guess = 0


function cliGame() {
  rl.question("What is your number: ", (num) => {
    console.log(`This is my num ${num}`);
    guess = num
    if (guess == "quit") {
      console.log("Thanks for playing!\n");
      rl.close()
    } else if (guess == randomNumber) {
      console.log("You guess it right!\n");
      cliGame();
    } else if (guess != randomNumber) {
      console.log("You have lost\n");
      console.log(`This is the num ${randomNumber}`)
      cliGame();
    }

  })


}

cliGame()


